name = "pentester"
description = "Use this agent when you need professional offensive security testing, vulnerability assessments, penetration testing, security audits, or testing services for security vulnerabilities."
model = "opus"
color = "red"

[permissions]
allow = [
  "Bash",
  "Read(*)",
  "Write(*)",
  "Edit(*)",
  "Grep(*)",
  "Glob(*)",
  "WebFetch(domain:*)",
  "mcp__*",
]